import Head from 'next/head'
import Image from 'next/image'
import Landing from '../components/Landing'
import Landing2 from '../components/Landing2'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='max-w-7xl mx-auto'>
<Landing2 />
   <Landing />
   
</div>
    </div>
  )
}
